### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by RajaBellebon** [sekhansen/text-mining-tutorial#2]
Hello @sekhansen ,

I am trying to play around with your tutorial.

After following all the installation (I am on Mac) , I try to run the code from : 
* Python 2.7 and the tutorial.py, I got : 
`Traceback (most recent call last):
  File "/Users/rbellebon/text-mining-tutorial/tutorial.py", line 9, in <module>
    import topicmodels
  File "/Users/rbellebon/text-mining-tutorial/topicmodels/__init__.py", line 5, in <module>
    from . import LDA
  File "/Users/rbellebon/text-mining-tutorial/topicmodels/LDA/__init__.py", line 2, in <module>
    from .gibbs import *
  File "/Users/rbellebon/text-mining-tutorial/topicmodels/LDA/gibbs.py", line 17, in <module>
    from topicmodels.samplers import samplers_lda
ImportError: dlopen(/Users/rbellebon/text-mining-tutorial/topicmodels/samplers/samplers_lda.so, 2): Symbol not found: _gsl_rng_mt19937
  Referenced from: /Users/rbellebon/text-mining-tutorial/topicmodels/samplers/samplers_lda.so
  Expected in: flat namespace`

* Python 3.6 and junyper notebook, when I execute import topicmodels, I got:

`ImportError: dlopen(/Users/rbellebon/text-mining-tutorial/topicmodels/samplers/samplers_lda.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /Users/rbellebon/text-mining-tutorial/topicmodels/samplers/samplers_lda.so
  Expected in: flat namespace
 in /Users/rbellebon/text-mining-tutorial/topicmodels/samplers/samplers_lda.so`

Any idea on what can be wrong?

Thanks in advance,

**Comment by sekhansen** [comment]
Thanks for the comment, in fact we are now setting the code up to allow easier installation with help from the Alan Turing Institute.  The new version should be ready by January.

**Comment by RajaBellebon** [comment]
Thanks @sekhansen ,I will watch the repo in this case and wait for the updated installation.
